GO
CREATE DATABASE ECHO
GO
USE ECHO
GO
CREATE TABLE Recordatorios(
ID_Recordatorios INT IDENTITY(1,1) PRIMARY KEY,
Nota VARCHAR(50),
Fecha DATE,
Hora NVARCHAR(20),
);
GO
SELECT * FROM Recordatorios
GO